### ISSUE TITLE
Erica's ANOVA tutorial tidying up

### ISSUE THREAD

**Issue by gndaskalova** [ourcodingclub/ourcodingclub.github.io#250]
Hi @ericazaja and @boyan-kar 

I have uploaded Erica's tutorial to the website, you can currently access it from this link - https://ourcodingclub.github.io/tutorials/anova/

I have also uploaded the images to the CC repo but you'll see that the links to the images need to be updated. Could either of you check out all the formatting and do the necessary edits? Here is the link to the file on Github - https://github.com/ourcodingclub/ourcodingclub.github.io/blob/master/_tutorials/anova.md and the images live in https://github.com/ourcodingclub/ourcodingclub.github.io/tree/master/assets/img/tutorials/anova

I thought it'd also be nice to use some coloured boxes for content that deserves to be highlighted, similar to how the Data Viz tutorial does it. You can see the code for the dataviz tutorial here and basically copy the code that makes the boxes https://github.com/ourcodingclub/ourcodingclub.github.io/edit/master/_tutorials/datavis.md

E.g.

```md
{% capture callout %}
Аll the files you need to complete this tutorial can be downloaded from [this Github repository](https://github.com/ourcodingclub/CC-4-Datavis). Clone and download the repo as a zip file, then unzip it.
{% endcapture %}
{% include callout.html content=callout colour=alert %}
```

The code that makes the boxs is the capture callout thing and there are a couple of different colours, here is another one:

```md
{% capture callout %}
## Good to know

If your axis labels need to contain special characters or superscript, you can get `ggplot2` to plot that, too. It might require some googling regarding your specific case, but for example, this code `ylabs(expression(paste('Grain yield','  ','(ton.', ha^-1, ')', sep='')))` will create a y axis with a label reading Grain yield (ton. ha<sup>-1</sup>).

To create additional space between an axis title and the axis itself, use `\n` when writing your title, and it will act as a line break.
{% endcapture %}
{% include callout.html content=callout colour="important" %}
```

Also, the code chunks need to have ```r instead of just r to get the R syntax highlighting. And perhaps better to have just one subheading, either Bonus or Extras, instead of both of them, for the additional parts at the end of the tutorial? And could make the sections of the bonus part be clickable buttons that expand? Like this one:

<img width="724" alt="Screen Shot 2021-02-17 at 11 10 19 AM" src="https://user-images.githubusercontent.com/22785802/108248227-ce54a000-7110-11eb-98ce-b3a02ad1bf89.png">

Otherwise, looks very neat and thank you Erica for putting the tutorial together! Once these changes are done, we can add the link to the tutorial on the Tutorials page (currently you can only access the tutorial if you have the link).

Hope you are doing well,
Gergana

**Comment by boyan-kar** [comment]
Thank you for this @gndaskalova !  I'm happy to do the required edits as I have Jekyll installed so I can test it quite easily.

**Comment by ericazaja** [comment]
@gndaskalova Hello and thanks for that!! I will work on the modifications you suggested. I will drop you a message once I'm done. 

@boyan-kar I will let you know if I need a hand, if that's ok? I'd like to complete the process by myself as much as possible, to learn how to do it. 

Thank you 
Erica

**Comment by gndaskalova** [comment]
@ericazaja you can also install Jekyll and ask @boyan-kar if you have any questions about it - basically that way you can preview your changes without them going online, so it saves you editing, refreshing the link, etc. https://docs.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll That way you also won't have to wait for someone to accept your pull request to see what your changes would look like.

**Comment by boyan-kar** [comment]
> 
> 
> @gndaskalova Hello and thanks for that!! I will work on the modifications you suggested. I will drop you a message once I'm done.
> 
> @boyan-kar I'll try to do the edits myself and I will let you know if I need a hand, if that's ok? I'd like to complete the process by myself as much as possible, to learn how to do it.
> 
> Thank you
> Erica

Hi @ericazaja ,
Sure! It's not difficult to edit at all since it's just markdown. The only issue you may have is that installing Jekyll is a bit tricky on Windows, if that's what you are using (I struggled with it).
