### ISSUE TITLE
CONTRIBUTING.md Guide and LICENSE are missing

### ISSUE THREAD

**Issue by coolbrg** [ourcodingclub/ourcodingclub.github.io#257]
Hi Folks,

Just wondering any open source project has the following two files:
- `CONTRIBUTING.md` 
- `LICENSE`

Did we miss or any other reason?

Thanks.

**Comment by EliseGallois** [comment]
Thank you @coolbrg for pointing this out! We had this information available but in other files. I've moved the relevant information into separate Contributing and License markdowns. All the best, Elise.
